[package]
name = "llvm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }
lazy_static = "1.4"
pest = "2.1"
pest_derive = "2.1"
